name: Build and Publish

on:
  push:
    branches:
      - 'dev/**'

jobs:
  windows:

    runs-on: windows-latest
    permissions: write-all
      
    steps:
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'
      
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - run: python build-server-client.py --platform win-x64

    - uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        files: |
          artifacts/*.zip
        name: "Release ${{ env.tag }}"
        tag_name: "${{ env.tag }}"
        fail_on_unmatched_files: true
        token: ${{ secrets.GITHUB_TOKEN }}
        generate_release_notes: false

  linux:

    runs-on: ubuntu-20.04
    permissions: write-all
      
    steps:
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
      
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'
      
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - run: python build-server-client.py --platform linux-x64

    - name: Create Github Release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        files: |
          artifacts/*.zip
        name: "Release ${{ env.tag }}"
        tag_name: "${{ env.tag }}"
        fail_on_unmatched_files: true
        token: ${{ secrets.GITHUB_TOKEN }}
        generate_release_notes: false

  android:

    runs-on: windows-latest
    permissions: write-all

    steps:
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
      
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'
      
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - run: python build-maui-client.py --framework net8.0-android
      env:
        ANDROID_SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }} 

    - uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        files: |
          artifacts/*.apk
          artifacts/*.aab
        name: "Release ${{ env.tag }}"
        tag_name: "${{ env.tag }}"
        fail_on_unmatched_files: false
        token: ${{ secrets.GITHUB_TOKEN }}
        generate_release_notes: false

    - uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
        packageName: com.axiolab.slowudppipe
        releaseFiles: artifacts/*.aab
        track: internal
        whatsNewDirectory: src/MauiClient/whats-new
